-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--   BRAINY AI — Complete & Verified Supabase Schema
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Instructions:
-- 1. Open your Supabase Dashboard: https://supabase.com/dashboard
-- 2. Select your project -> Click on "SQL Editor" in the left sidebar.
-- 3. Click "New query", paste this entire file, and click "Run".
-- This guarantees every user login, chat session, message, and stats are stored!

-- ── 1. USER LOGINS TABLE ──────────────────────────────────
-- Records every login event (Web, Google, Telegram) with IP & user agent
create table if not exists public.user_logins (
  id          bigint generated by default as identity primary key,
  user_id     bigint not null,
  username    text default '',
  first_name  text default '',
  login_type  text not null default 'web',  -- 'web', 'google', 'telegram_webapp'
  ip_address  text default '',
  user_agent  text default '',
  logged_at   timestamptz default now()
);

create index if not exists idx_user_logins_user_id on public.user_logins(user_id);
create index if not exists idx_user_logins_logged_at on public.user_logins(logged_at desc);

-- ── 2. USER MEMORY & GAMIFICATION STATS ───────────────────
-- Stores student level, question count, quiz score, streak, and saved liked notes
create table if not exists public.user_memory (
  user_id      bigint primary key,
  first_name   text default '',
  username     text default '',
  level        text default '1',
  score        int default 0,
  total        int default 0,
  streak       int default 1,
  history      jsonb default '[]'::jsonb,
  ask_history  jsonb default '[]'::jsonb,
  liked_notes  jsonb default '[]'::jsonb,
  joined_at    timestamptz default now(),
  updated_at   timestamptz default now()
);

create index if not exists idx_user_memory_user_id on public.user_memory(user_id);

-- ── 3. CHAT SESSIONS TABLE ────────────────────────────────
-- Stores active and historical study sessions for the web app
create table if not exists public.chat_sessions (
  id          uuid primary key default gen_random_uuid(),
  user_id     bigint not null,
  title       text not null default 'New Study Session',
  created_at  timestamptz default now()
);

create index if not exists idx_chat_sessions_user_id on public.chat_sessions(user_id);
create index if not exists idx_chat_sessions_created_at on public.chat_sessions(created_at desc);

-- ── 4. CHAT MESSAGES TABLE ────────────────────────────────
-- Stores every individual conversation message (user & assistant)
create table if not exists public.chat_messages (
  id          bigint generated by default as identity primary key,
  session_id  uuid not null references public.chat_sessions(id) on delete cascade,
  role        text not null check (role in ('user', 'assistant', 'system')),
  content     text not null,
  created_at  timestamptz default now()
);

create index if not exists idx_chat_messages_session_id on public.chat_messages(session_id);
create index if not exists idx_chat_messages_created_at on public.chat_messages(created_at asc);

-- ── 5. TELEGRAM BOT USERS ─────────────────────────────────
-- Stores Telegram users for broadcast, reminders, and daily check-ins
create table if not exists public.bot_users (
  chat_id     bigint primary key,
  chat_type   text default 'private',
  username    text,
  first_name  text,
  joined_at   timestamptz default now(),
  last_seen   timestamptz default now()
);

-- ── 6. QUIZ POLLS & LEADERBOARDS ──────────────────────────
create table if not exists public.quiz_polls (
  poll_id            text primary key,
  chat_id            bigint not null,
  correct_option_id  int not null,
  subject            text default '',
  created_at         timestamptz default now()
);

create table if not exists public.quiz_scores (
  chat_id         bigint not null,
  user_id         bigint not null,
  username        text,
  correct_count   int default 0,
  total_answered  int default 0,
  updated_at      timestamptz default now(),
  primary key (chat_id, user_id)
);

-- ── 7. ROW LEVEL SECURITY (RLS) POLICIES ──────────────────
-- Since Brainy uses the SUPABASE_SERVICE_ROLE_KEY on the backend,
-- queries bypass RLS. These policies ensure safe access if anon key is ever used.

alter table public.user_logins enable row level security;
alter table public.user_memory enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.bot_users enable row level security;
alter table public.quiz_polls enable row level security;
alter table public.quiz_scores enable row level security;

-- Allow service_role full permissions (default in Supabase, explicit for clarity)
create policy "Service Role Full Access Logins" on public.user_logins for all using (true);
create policy "Service Role Full Access Memory" on public.user_memory for all using (true);
create policy "Service Role Full Access Sessions" on public.chat_sessions for all using (true);
create policy "Service Role Full Access Messages" on public.chat_messages for all using (true);
create policy "Service Role Full Access Bot Users" on public.bot_users for all using (true);
create policy "Service Role Full Access Quiz Polls" on public.quiz_polls for all using (true);
create policy "Service Role Full Access Quiz Scores" on public.quiz_scores for all using (true);
